### ISSUE TITLE
多CK问题

### ISSUE THREAD

**Issue by 546220777** [passerby-b/JDDJ#1]
圈X boxjs里面按照要求填多CK   获取不到  一个CK正常

**Comment by 717785320** [comment]
多个ck用,分开;填写完后用qx运行脚本看报什么错

**Comment by 546220777** [comment]
> 多个ck用,分开;填写完后用qx运行脚本看报什么错

不报错  运行直接logs:    done！

**Comment by 717785320** [comment]
那可能是你ck没写进去,进boxjs数据查看key输入jddj_cookies看有没有ck

**Comment by 546220777** [comment]
> 那可能是你ck没写进去,进boxjs数据查看key输入jddj_cookies看有没有ck

手机运行不是不需要jddj_cookies这个吗  我是直接在boxjs里填ck   单个正常  2个就不正常了 ！

**Comment by 717785320** [comment]
逗号隔开,别换行,也别用单引号或双引号包着,boxjs上我写错了

**Comment by 546220777** [comment]
我就是

> 逗号隔开,别换行,也别用单引号或双引号包着,boxjs上我写错了

deviceid_pdj_jd=xxx-xxx-xxx;o2o_m_h5_sid=xxx-xxx-xxx,deviceid_pdj_jd=xxx-xxx-xxx;o2o_m_h5_sid=xxx-xxx-xxx    我是这样写的

**Comment by 717785320** [comment]
更新一下脚本再试

**Comment by 546220777** [comment]
> 更新一下脚本
更新后可以了  谢谢大佬

**Comment by 546220777** [comment]
> 更新一下脚本再试

还是有点问题   jddj_fruit_collectWater.js  jddj_fruit.js这两个脚本多CK还是获取不到  其他几个脚本正常了

**Comment by 717785320** [comment]
再更新试下

**Comment by 546220777** [comment]
> 再更新试下

这两个还是不行

**Comment by 717785320** [comment]
看更新到了没有,我这边亲测是好的

**Comment by 546220777** [comment]
> 看更新到了没有,我这边亲测是好的

现在好了  刚更新早了  你这边还没更新

**Comment by passerby-b** [comment]
解决
