### ISSUE TITLE
求CK怎么填写，我按照要求填写，本地node.js运行失败 

### ISSUE THREAD

**Issue by qxy0789** [passerby-b/JDDJ#2]
cookie只要里面的deviceid_pdj_jd=xxx-xxx-xxx;o2o_m_h5_sid=xxx-xxx-xxx关键信息，我按照这个填写，运行出现错误：SyntaxError: Invalid or unexpected token!

**Comment by 717785320** [comment]
nodejs在jddj_cookie.js里填cookie

**Comment by passerby-b** [comment]
...
