### ISSUE TITLE
每天显示助力码，怎么使用

### ISSUE THREAD

**Issue by yxguy** [passerby-b/JDDJ#30]
每天显示助力码，怎么使用，需要把助力码填写到哪里，还是有专门的变量，望大神们解答，感谢。

**Comment by passerby-b** [comment]
电报群机器人提交

**Comment by yxguy** [comment]
> 电报群机器人提交

感谢大佬解答，电报群我进不去了，怎么放行？（昵称yxguy)

**Comment by xukf2000** [comment]
求指点下，tg显示组私有了，无法加入，请问怎么加入进去

**Comment by passerby-b** [comment]
并没有封你们的号,重新进

**Comment by xukf2000** [comment]
![07893CCB-D6A2-4188-9B28-067AE3EB105F](https://user-images.githubusercontent.com/34463908/120075539-49e0c880-c0d4-11eb-89b0-401915c985cd.png)
帮看看图片显示的是组私有 进不去
