### ISSUE TITLE
运行jddj_fruit_code.js报错

### ISSUE THREAD

**Issue by 474903784** [passerby-b/JDDJ#38]
开始执行... 2021/6/15下午5:10:53

更新任务状态成功
 ❌失败! 原因:ReferenceError: $ is not defined! 
(node:359) UnhandledPromiseRejectionWarning: ReferenceError: $ is not defined
    at eval (eval at <anonymous> (/ql/scripts/passerby-b_JDDJ_jddj_fruit_code.js:3:1), <anonymous>:1:2351)
    at <anonymous>
(Use `node --trace-warnings ...` to show where the warning was created)
(node:359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:359) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
更新任务状态成功

执行结束...

我在青龙上运行报错，这个是啥问题呢？

**Comment by passerby-b** [comment]
我可从来没说这个脚本是拿来运行的
