### ISSUE TITLE
(node:27841) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected identifier     at eval (eval at <anonymous> (/jd/scripts/jddj_fruit.js:25:30), <anonymous>:3:353)

### ISSUE THREAD

**Issue by piaoyun** [passerby-b/JDDJ#40]
(node:27841) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected identifier
    at eval (eval at <anonymous> (/jd/scripts/jddj_fruit.js:25:30), <anonymous>:3:353)
    at /jd/scripts/jddj_fruit.js:25:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by passerby-b** [comment]
更新脚本
