### ISSUE TITLE
【bug】未选择水果的账号，脚本也会做任务

### ISSUE THREAD

**Issue by lxr760** [passerby-b/JDDJ#48]
日志如下：

前面的任务都做完了，到最后浇水的时候才判断活动不存在

应该改一下，在最开始判断。如果这个号里面没有选水果，直接就跳过这个账号  不执行了

★★★★★开始执行第1个账号,共1个账号★★★★★
●●●***●●●

【收玻璃瓶水滴】:水瓶中有:1水滴

【收玻璃瓶水滴】:水瓶已经收取过

【连续签到任务】: 任务已完成,跳过做任务

【连续签到任务】: 奖励已领取,跳过领奖励

【助力任务】: 脚本无法执行此任务或任务不需要主动完成

【助力任务】: 任务未完成,跳过领奖励

【每日水滴奖励】: 任务已完成,跳过做任务

【每日水滴奖励】: 奖励已领取,跳过领奖励

【下单领水滴】: 脚本无法执行此任务或任务不需要主动完成

【下单领水滴】: 任务未完成,跳过领奖励

【邀请好友种水果】: 脚本无法执行此任务或任务不需要主动完成

【邀请好友种水果】: 任务未完成,跳过领奖励

【逛永辉超市领水滴】: 任务已完成,跳过做任务

【逛永辉超市领水滴】: 奖励已领取,跳过领奖励

【定时领水滴】: 任务已领取或不需要领取

任务完成【定时领水滴】:成功,奖励:43

领取奖励【定时领水滴】:未达到领取奖励的条件

【浏览商品得水滴】: 任务已完成,跳过做任务

【浏览商品得水滴】: 奖励已领取,跳过领奖励

【开通华润万家会员】: 脚本无法执行此任务或任务不需要主动完成

【开通华润万家会员】: 任务未完成,跳过领奖励

【到家签到】:您今天已签到，请勿重复操作！

【去签到领水滴】: 任务未完成,跳过领奖励

【天天领金贴】: 任务已完成,跳过做任务

【天天领金贴】: 奖励已领取,跳过领奖励

【去领免费商品】: 任务已完成,跳过做任务

【去领免费商品】: 奖励已领取,跳过领奖励

【逛沃尔玛领水滴】: 任务已完成,跳过做任务

【逛沃尔玛领水滴】: 奖励已领取,跳过领奖励

【超级多单奖励】: 脚本无法执行此任务或任务不需要主动完成

【超级多单奖励】: 任务未完成,跳过领奖励

【完成10次浇水任务】: 任务已领取或不需要领取

【完成10次浇水任务】: 任务未完成,跳过领奖励

【限时！再浇水15次领水滴】: 任务已领取或不需要领取

【限时！再浇水15次领水滴】: 任务未完成,跳过领奖励

【助力】:失败

【助力】:失败

【助力】:失败

【助力】:失败

【助力】:失败

**********开始执行第1次浇水**********

【浇水】:活动不存在

**Comment by passerby-b** [comment]
种水果是必须的,还需要脚本去判断

**Comment by lxr760** [comment]
> 种水果是必须的,还需要脚本去判断

我跑的号10个不到  里面有选了水果的  也有没选的。我想说如果某个账号没有选水果，就跳过不做任务了，直接到下一个账号
