### ISSUE TITLE
ios上的小火箭应该怎样抓取cookie呢？

### ISSUE THREAD

**Issue by XuuKoo** [passerby-b/JDDJ#52]
之前用的jddj_getck.js抓取cookie，直到某天脚本开始兼容jdcookie.js后，新脚本就实在提示cookie过期或者失效，无奈一直使用的老版本的脚本。

**Comment by passerby-b** [comment]
用jd ck不好吗

**Comment by XuuKoo** [comment]
> 
> 
> 用jd ck不好吗

ios上jd cookie是用https://github.com/NobyDa/Script/blob/master/JD-DailyBonus/JD_DailyBonus.js这个抓的，但是到家脚本并不能识别。

**Comment by passerby-b** [comment]
用boxjs订阅我的脚本库,打开脚本填写ck
