### ISSUE TITLE
jddj_fruit.js 缺少signKeyV1验证参数值，导致浇水失败

### ISSUE THREAD

**Issue by rubnet** [passerby-b/JDDJ#54]
signKeyV1签名参考
https://github.com/simonchen/JDDJ_Reverse

**Comment by rubnet** [comment]
签名算法
https://github.com/ClassmateLin/jd_scripts/blob/c9519bcad21ffa1429d5a0b7bbb47069bba417de/utils/dj_init.py

**Comment by passerby-b** [comment]
ok
