### ISSUE TITLE
建议支持从环境变量导入 Cookie

### ISSUE THREAD

**Issue by RikudouPatrickstar** [passerby-b/JDDJ#6]
建议支持从环境变量导入 Cookie，以便于统一管理 Cookie 及推送所需的变量等
可参考：
https://github.com/ITdesk01/JD_Script/blob/main/JSON/jdCookie.js

**Comment by passerby-b** [comment]
这个不打算搞,京东到家和京东ck不通用,这样搞怕跟京东有冲突,最主要的是懒

**Comment by RikudouPatrickstar** [comment]
好的吧，我是想格外封装一个 Docker 运行这套京东到家脚本的，支持环境变量导入cookie的话，管理更方便点
