### ISSUE TITLE
请问能否设置为均等助力呢，怎么设置呢？

### ISSUE THREAD

**Issue by XXIN0** [passerby-b/JDDJ#65]
如题，谢谢！

**Comment by passerby-b** [comment]
均等助力是什么意思?

**Comment by XXIN0** [comment]
每个人的助力机会相等，我看现在的脚本只给第一个人助力来着，后面的人就没得到过助力

**Comment by passerby-b** [comment]
你再仔细看看代码逻辑

**Comment by XXIN0** [comment]
![image](https://user-images.githubusercontent.com/41498132/142140288-6ee6976b-809b-4068-99e4-32c5036edf3e.png)
内容是这样的，我也看不懂，初学者，打扰了。。。

**Comment by passerby-b** [comment]
助力码是随机从池子里取的,看运气

**Comment by XXIN0** [comment]
好的，谢谢。

**Comment by passerby-b** [comment]
你这是别人修改版,不是我的原版

**Comment by XXIN0** [comment]
哦哦，好的，我是从faker2里面拉的
