### ISSUE TITLE
怎样能屏蔽推送呢？

### ISSUE THREAD

**Issue by whilr** [passerby-b/JDDJ#66]
我设置isnotify=false ，可是还是能收到推送。。。问下想关闭推送，这个怎么设置呢？

**Comment by passerby-b** [comment]
更新脚本

**Comment by whilr** [comment]
谢谢作者大大，更新后脚本一直运行，结束不了了。。。看日志最后面显示done，还在运行

**Comment by passerby-b** [comment]
用什么跑的?更新之前没问题?

**Comment by whilr** [comment]
QL面板，之前没问题。。。
