### ISSUE TITLE
请问能否开发多账号相互助力

### ISSUE THREAD

**Issue by ryan016** [passerby-b/JDDJ#9]
如何获取多账号之间的助力码呢？谢谢！

**Comment by passerby-b** [comment]
脚本里实际已经实现了助力功能，不过互助码每天都在变太麻烦了没开放

**Comment by ryan016** [comment]
> 脚本里实际已经实现了助力功能，不过互助码每天都在变太麻烦了没开放

希望能显示各自的助力码，每天手动设置都可以，谢谢了！！！

**Comment by wudongdefeng** [comment]
> > 脚本里实际已经实现了助力功能，不过互助码每天都在变太麻烦了没开放
> 
> 希望能显示各自的助力码，每天手动设置都可以，谢谢了！！！

希望像水果群那样，内置助力库，每天提交

**Comment by passerby-b** [comment]
那是需要买台服务器来存互助码的

**Comment by slj844909754** [comment]
互助码格式怎么填写呢？
